//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Game/Data/Technical/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Game.Input
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""DevCheats"",
            ""id"": ""c4d6b50d-3ed4-45db-a72b-7aa61d1158cc"",
            ""actions"": [
                {
                    ""name"": ""NextWave"",
                    ""type"": ""Button"",
                    ""id"": ""a205ddde-172f-45cb-9521-b33864dee065"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextLevel"",
                    ""type"": ""Button"",
                    ""id"": ""3946efb7-a03f-490d-b620-18111b4877e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevLevel"",
                    ""type"": ""Button"",
                    ""id"": ""f8fda95d-bace-42cb-82a0-76c4f94aef05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuyUnit"",
                    ""type"": ""Button"",
                    ""id"": ""e36d820e-5aed-46cb-8430-c8624448bad5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddSoftCurrency"",
                    ""type"": ""Button"",
                    ""id"": ""47560b4f-7371-410f-91bb-2624a09de6d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddSummonCurrency"",
                    ""type"": ""Button"",
                    ""id"": ""f283a0b2-ff97-4a3a-8f40-a22a0db38a0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveGameSaves"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15c0bd2a-951c-4e6d-9089-6a185961b91e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""0a458f3c-c094-4f2c-b8f7-5cbd1cc53765"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c34a49d4-c108-4e2c-893b-a903d5045b13"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextWave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df0ce860-316c-4aa5-81e9-b773a6295194"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff6b4f8b-daa1-4c70-9213-3eecbb28a5c7"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4926dfa-765c-4597-9acd-fe4b7cd9be96"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuyUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa0a49b9-ca52-45d8-9f07-b7b022c933e8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddSoftCurrency"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf19889-84d1-471e-9c7f-d74e0227f3c5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddSummonCurrency"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""R [Keyboard]"",
                    ""id"": ""04dbef62-1695-4d9d-9547-c5b4dccff747"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveGameSaves"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e72a1967-b063-428d-ae2e-81601a190881"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveGameSaves"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""26cfb299-a213-42d9-bd35-7c2054fc3332"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveGameSaves"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""14f40531-8320-4bcf-b17a-9a5ee5a87994"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // DevCheats
            m_DevCheats = asset.FindActionMap("DevCheats", throwIfNotFound: true);
            m_DevCheats_NextWave = m_DevCheats.FindAction("NextWave", throwIfNotFound: true);
            m_DevCheats_NextLevel = m_DevCheats.FindAction("NextLevel", throwIfNotFound: true);
            m_DevCheats_PrevLevel = m_DevCheats.FindAction("PrevLevel", throwIfNotFound: true);
            m_DevCheats_BuyUnit = m_DevCheats.FindAction("BuyUnit", throwIfNotFound: true);
            m_DevCheats_AddSoftCurrency = m_DevCheats.FindAction("AddSoftCurrency", throwIfNotFound: true);
            m_DevCheats_AddSummonCurrency = m_DevCheats.FindAction("AddSummonCurrency", throwIfNotFound: true);
            m_DevCheats_RemoveGameSaves = m_DevCheats.FindAction("RemoveGameSaves", throwIfNotFound: true);
            m_DevCheats_Shoot = m_DevCheats.FindAction("Shoot", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // DevCheats
        private readonly InputActionMap m_DevCheats;
        private IDevCheatsActions m_DevCheatsActionsCallbackInterface;
        private readonly InputAction m_DevCheats_NextWave;
        private readonly InputAction m_DevCheats_NextLevel;
        private readonly InputAction m_DevCheats_PrevLevel;
        private readonly InputAction m_DevCheats_BuyUnit;
        private readonly InputAction m_DevCheats_AddSoftCurrency;
        private readonly InputAction m_DevCheats_AddSummonCurrency;
        private readonly InputAction m_DevCheats_RemoveGameSaves;
        private readonly InputAction m_DevCheats_Shoot;
        public struct DevCheatsActions
        {
            private @Controls m_Wrapper;
            public DevCheatsActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @NextWave => m_Wrapper.m_DevCheats_NextWave;
            public InputAction @NextLevel => m_Wrapper.m_DevCheats_NextLevel;
            public InputAction @PrevLevel => m_Wrapper.m_DevCheats_PrevLevel;
            public InputAction @BuyUnit => m_Wrapper.m_DevCheats_BuyUnit;
            public InputAction @AddSoftCurrency => m_Wrapper.m_DevCheats_AddSoftCurrency;
            public InputAction @AddSummonCurrency => m_Wrapper.m_DevCheats_AddSummonCurrency;
            public InputAction @RemoveGameSaves => m_Wrapper.m_DevCheats_RemoveGameSaves;
            public InputAction @Shoot => m_Wrapper.m_DevCheats_Shoot;
            public InputActionMap Get() { return m_Wrapper.m_DevCheats; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DevCheatsActions set) { return set.Get(); }
            public void SetCallbacks(IDevCheatsActions instance)
            {
                if (m_Wrapper.m_DevCheatsActionsCallbackInterface != null)
                {
                    @NextWave.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextWave;
                    @NextWave.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextWave;
                    @NextWave.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextWave;
                    @NextLevel.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextLevel;
                    @NextLevel.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextLevel;
                    @NextLevel.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnNextLevel;
                    @PrevLevel.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnPrevLevel;
                    @PrevLevel.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnPrevLevel;
                    @PrevLevel.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnPrevLevel;
                    @BuyUnit.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnBuyUnit;
                    @BuyUnit.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnBuyUnit;
                    @BuyUnit.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnBuyUnit;
                    @AddSoftCurrency.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSoftCurrency;
                    @AddSoftCurrency.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSoftCurrency;
                    @AddSoftCurrency.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSoftCurrency;
                    @AddSummonCurrency.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSummonCurrency;
                    @AddSummonCurrency.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSummonCurrency;
                    @AddSummonCurrency.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnAddSummonCurrency;
                    @RemoveGameSaves.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnRemoveGameSaves;
                    @RemoveGameSaves.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnRemoveGameSaves;
                    @RemoveGameSaves.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnRemoveGameSaves;
                    @Shoot.started -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnShoot;
                    @Shoot.performed -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnShoot;
                    @Shoot.canceled -= m_Wrapper.m_DevCheatsActionsCallbackInterface.OnShoot;
                }
                m_Wrapper.m_DevCheatsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @NextWave.started += instance.OnNextWave;
                    @NextWave.performed += instance.OnNextWave;
                    @NextWave.canceled += instance.OnNextWave;
                    @NextLevel.started += instance.OnNextLevel;
                    @NextLevel.performed += instance.OnNextLevel;
                    @NextLevel.canceled += instance.OnNextLevel;
                    @PrevLevel.started += instance.OnPrevLevel;
                    @PrevLevel.performed += instance.OnPrevLevel;
                    @PrevLevel.canceled += instance.OnPrevLevel;
                    @BuyUnit.started += instance.OnBuyUnit;
                    @BuyUnit.performed += instance.OnBuyUnit;
                    @BuyUnit.canceled += instance.OnBuyUnit;
                    @AddSoftCurrency.started += instance.OnAddSoftCurrency;
                    @AddSoftCurrency.performed += instance.OnAddSoftCurrency;
                    @AddSoftCurrency.canceled += instance.OnAddSoftCurrency;
                    @AddSummonCurrency.started += instance.OnAddSummonCurrency;
                    @AddSummonCurrency.performed += instance.OnAddSummonCurrency;
                    @AddSummonCurrency.canceled += instance.OnAddSummonCurrency;
                    @RemoveGameSaves.started += instance.OnRemoveGameSaves;
                    @RemoveGameSaves.performed += instance.OnRemoveGameSaves;
                    @RemoveGameSaves.canceled += instance.OnRemoveGameSaves;
                    @Shoot.started += instance.OnShoot;
                    @Shoot.performed += instance.OnShoot;
                    @Shoot.canceled += instance.OnShoot;
                }
            }
        }
        public DevCheatsActions @DevCheats => new DevCheatsActions(this);
        public interface IDevCheatsActions
        {
            void OnNextWave(InputAction.CallbackContext context);
            void OnNextLevel(InputAction.CallbackContext context);
            void OnPrevLevel(InputAction.CallbackContext context);
            void OnBuyUnit(InputAction.CallbackContext context);
            void OnAddSoftCurrency(InputAction.CallbackContext context);
            void OnAddSummonCurrency(InputAction.CallbackContext context);
            void OnRemoveGameSaves(InputAction.CallbackContext context);
            void OnShoot(InputAction.CallbackContext context);
        }
    }
}
